stages:
- build
- release

#---------------
# Build
#---------------

.build-docker:
  stage: build
  image: ${REGISTRY_URL}/factory-ci-runner:build-package
  script:
    - make -C docker build deliver PHP_VERSION=$PHP_VERSION
    - make -C docker clean PHP_VERSION=$PHP_VERSION
  environment:
    name: snap
  artifacts:
    paths:
      - "docker/factory-cli.manifest"
      - "docker/factory-fpm.manifest"
      - "docker/factory-web.manifest"
  only:
    refs:
      - tags
      - main
  tags:
    - infrav3-dind

build-docker:7.4:
  extends: .build-docker
  variables:
    PHP_VERSION: "7.4"

build-docker:8.1:
  extends: .build-docker
  variables:
    PHP_VERSION: "8.1"

build-docker:8.2:
  extends: .build-docker
  variables:
    PHP_VERSION: "8.2"

build-docker:8.3:
  extends: .build-docker
  variables:
    PHP_VERSION: "8.3"

build-docker:8.4:
  extends: .build-docker
  variables:
    PHP_VERSION: "8.4"

#-------------
# Release
#-------------

.release:
  image: ${REGISTRY_URL}/factory-ci-runner:build-package
  stage: release
  script:
    - FACTORY_MANIFEST="docker/factory-cli.manifest" release-image.sh liz-php-cli-$PHP_VERSION
    - FACTORY_MANIFEST="docker/factory-fpm.manifest" release-image.sh liz-php-fpm-$PHP_VERSION
    - FACTORY_MANIFEST="docker/factory-web.manifest" release-image.sh liz-php-web-$PHP_VERSION
    - FACTORY_MANIFEST="docker/factory-cli.manifest" push-to-docker-hub.sh --clean
    - FACTORY_MANIFEST="docker/factory-fpm.manifest" push-to-docker-hub.sh --clean
    - FACTORY_MANIFEST="docker/factory-web.manifest" push-to-docker-hub.sh --clean
  environment:
    name: production
  when: manual
  only:
    refs:
      - tags
  tags:
    - infrav3-dind

release:7.4:
  extends: .release
  variables:
    PHP_VERSION: "7.4"
  dependencies:
    - build-docker:7.4

release:8.1:
  extends: .release
  variables:
    PHP_VERSION: "8.1"
  dependencies:
    - build-docker:8.1

release:8.2:
  extends: .release
  variables:
    PHP_VERSION: "8.2"
  dependencies:
    - build-docker:8.2

release:8.3:
  extends: .release
  variables:
    PHP_VERSION: "8.3"
  dependencies:
    - build-docker:8.3

release:8.4:
  extends: .release
  variables:
    PHP_VERSION: "8.4"
  dependencies:
    - build-docker:8.4


